---
 - name: Provision an EC instance
   hosts: local
   connection: local
   gather_facts: false
   tags: provisioning
   roles:
       - role_ec2

 - name: Configure EC2 instance
   hosts: webserver
   connection: local
   tags: Config
   roles:
       # role_config