---
-
  name: "read ip address from file"
  

-
  name: "terminate instances which created"
  ec2:
    instance_ids: "{{ ['id']|map('extract', ec2.instances)|list }}"
    region: "{{region}}"
    state: stopped
    wait: True
    vpc_subnet_id: "{{subnet_id}}"
    assign_public_ip: true
